services:
  wgp:
    build:
      context: .
      dockerfile: Dockerfile

    image: wan2gp:latest
    ports:
      - "127.0.0.1:${WGP_PORT:-7860}:7860"
    volumes:
      - "${WGP_LORA_DIR:-${WGP_DIR}}:/workspace/Wan2GP/loras"
      - "${WGP_LORA_DIR:-${WGP_DIR}}:/workspace/Wan2GP/loras_i2v"
      - "${OUTPUT_DIR:-${WGP_DIR}}:/workspace/Wan2GP/outputs"
      - "${CKPT_DIR:-${WGP_DIR}}:/workspace/Wan2GP/ckpts"
      - "${WGP_CONF:-${WGP_DIR}}:/workspace/Wan2GP/wgp_config.json"
    command: python wgp.py --server-port 7860 --listen
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${WGPU_ID:-0}"]
              capabilities: [gpu]

volumes:
  wan2gp:

