# .github/workflows/build-wan2gp.yml
name: Build and Push wan2gp

on:
  push:
    branch:
      - main
  # schedule:
      - cron: "5 6 * * *"   # once per day at 06:05 UTC
  workflow_dispatch:       # still allow manual runs

env:
  # ⬇️ Set these to the upstream repo you want to watch
  UPSTREAM_OWNER: deepbeepmeep
  UPSTREAM_REPO: wan2gp
  UPSTREAM_REF: main

jobs:
  build-and-push:
    runs-on: [self-hosted, 16gb-mem]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest upstream commit SHA
        id: upstream
        uses: actions/github-script@v7
        with:
          script: |
            const owner = process.env.UPSTREAM_OWNER;
            const repo  = process.env.UPSTREAM_REPO;
            const ref   = process.env.UPSTREAM_REF;

            // Get the commit at the ref (branch)
            const { data } = await github.request('GET /repos/{owner}/{repo}/commits/{ref}', {
              owner, repo, ref
            });

            core.setOutput('sha', data.sha);
            core.info(`Latest upstream ${owner}/${repo}@${ref} = ${data.sha}`);

      - name: Cache last-seen upstream SHA
        id: cache
        uses: actions/cache@v4
        with:
          path: .upstream-last-sha
          key: upstream-${{ steps.upstream.outputs.sha }}

      - name: Show and record new upstream SHA
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "New upstream commit: ${{ steps.upstream.outputs.sha }}"
          echo "${{ steps.upstream.outputs.sha }}" > .upstream-last-sha

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v3
        with:
          username: marksverdhei
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push wan2gp image
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: wan2gp/Dockerfile
          push: true
          tags: |
            marksverdhei/wan2gp:latest
            marksverdhei/wan2gp:${{ steps.upstream.outputs.sha }}
