name: Build and Push automatic1111 webui
on:
  push:
    branches:
      - main
    paths:
      - 'automatic1111/Dockerfile'
      - '.github/workflows/build-a1111.yml'

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted, 16gb-mem]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: marksverdhei
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push a1111 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: automatic1111/Dockerfile
          push: true
          tags: |
            marksverdhei/automatic1111-webui:latest
            marksverdhei/automatic1111-webui:${{ github.sha }}
