name: Build and Push YuE
on:
  push:
    branches:
      - main
      - yue
    paths:
      - 'yue/Dockerfile'
      - '.github/workflows/build-yue.yml'

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted, 16gb-mem]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: marksverdhei
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push yue image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: yue/Dockerfile
          push: true
          tags: |
            marksverdhei/yue:latest
            marksverdhei/yue:${{ github.sha }}
