name: Build and Push wan2gp
on:
  push:
    branches:
      - main
    paths:
      - 'wan2gp/Dockerfile'
      - '.github/workflows/build-wan2gp.yml'

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted, 16gb-mem]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: marksverdhei
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push wan2gp image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: wan2gp/Dockerfile
          push: true
          tags: |
            marksverdhei/wan2gp:latest
            marksverdhei/wan2gp:${{ github.sha }}

      - name: Build and push wan2gp image with marksverdhei fork
        uses: docker/build-push-action@v5
        with:
          context: .
          file: wan2gp/Dockerfile
          push: true
          build-args: |
            FORK_OWNER=marksverdhei
          tags: |
            marksverdhei/wan2gp:marksverdhei
            marksverdhei/wan2gp:marksverdhei-${{ github.sha }}
